import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import BottomNavigation from "./components/layout/BottomNavigation";

const banglaRegular = localFont({
  variable: "--font-bangla-regular",
  src: [
    {
      path: "./fonts/Li_Purno_Pran.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ekatan | Ecommerce",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // ensure the body is at least viewport height so descendant height-full works
        className={`${geistSans.variable} ${geistMono.variable} ${banglaRegular.variable} antialiased bg-main min-h-screen w-full`}
      >
        <Navbar />
        <div className=" pt-16">{children}</div>
        <Footer />
        <BottomNavigation />
      </body>
    </html>
  );
}
